/**
 * Differential test: the TypeScript engine must agree with the Python one.
 *
 * The fixture is generated by tools/parity_dump.py from a seeded synthetic
 * corpus - every course type, marks present and absent, attendance either side
 * of both thresholds, duty leave inside and outside the cap. Hand-written
 * tests share the blind spots of whoever wrote the code; this does not.
 *
 * Regenerate the fixture whenever the Python engine changes, and never edit it
 * by hand - a fixture edited to make a test pass proves nothing.
 *
 * Some fields are excluded from the comparison below, because the Python
 * oracle carries the very defects p0-engine-correctness fixes: its fixture
 * values for them are the wrong answer, not the spec. Regenerating the
 * fixture would only re-pin these tests to the bugs, so it stays byte
 * identical and the comparison narrows instead. Direct coverage for
 * everything dropped lives in `core.test.ts`.
 *
 *   - `attendance`, `eligible`, `attMarks` (task 1): the oracle reads a blank
 *     attendance field as a full 100%.
 *   - `cie`, `total`, `grade`, `failedReason`, `needPass`, `needTarget`,
 *     `maxPossibleGrade`, `status` (task 1): the oracle never spends
 *     attendance inside the CIE, so every number derived from the CIE differs
 *     by up to the 5 marks of R 7.5.ii. The same goes for the semester
 *     rollup's SGPA, percentage, at-risk and impossible fields.
 *   - `plan`, `attBand` (task 8): the oracle credits duty leave once against
 *     today's `held`, then asks how many classes may be skipped or must be
 *     attended - questions whose `held`, and so whose 10% relaxation, is
 *     larger. Its `skip` and `attend` are answers to a denominator that no
 *     longer applies. `core.test.ts` covers both branches directly, under
 *     "duty leave", against figures derived by hand from R 6.3.ii.
 *
 * What is left is thin, and worth saying plainly: after this narrowing the
 * comparison is the maxima, the raw ESE, the credits, the assessed flag and
 * the chosen target - the fields no p0 fix touches. It is a guard against
 * regressing the parts nobody set out to change, not evidence the engine is
 * right. The evidence for that lives in `core.test.ts`.
 */
import { describe, expect, it } from "vitest";
import fixture from "./parity.json";
import { evaluate, summarise } from "../index";
import type { Course, Evaluation } from "../types";

interface Expected {
  cie: number; cieMax: number; eseMax: number; ese: number | null;
  eseCutoff: number; total: number | null; grade: string | null;
  failedReason: string; attendance: number; eligible: boolean;
  assessed: boolean; attMarks: number | null; credits: number;
  needPass: { value: number; possible: boolean; text: string; binding: string };
  needTarget: { value: number; possible: boolean; text: string; binding: string };
  target: string; maxPossibleGrade: string; status: string;
  plan: Record<string, unknown> | null;
  attBand: Record<string, unknown> | null;
}

const courses = fixture.courses as unknown as Array<{ course: Course; expected: Expected }>;
const semesters = fixture.semesters as unknown as Array<{
  courses: Course[];
  summary: Record<string, unknown>;
}>;

/**
 * Reduce an Evaluation to exactly the fields the fixture records, minus the
 * ones the Python oracle gets wrong (see file header).
 */
function slim(ev: Evaluation) {
  return {
    cieMax: ev.cieMax, eseMax: ev.eseMax, ese: ev.ese, eseCutoff: ev.eseCutoff,
    assessed: ev.assessed, credits: ev.credits, target: ev.target,
  };
}

/** Same fields as `slim`, pulled off the Python fixture's recorded shape. */
function slimExpected(expected: Expected) {
  const {
    attendance: _attendance, eligible: _eligible, attMarks: _attMarks,
    cie: _cie, total: _total, grade: _grade, failedReason: _failedReason,
    needPass: _needPass, needTarget: _needTarget,
    maxPossibleGrade: _maxPossibleGrade, status: _status,
    plan: _plan, attBand: _attBand, ...rest
  } = expected;
  return rest;
}

/**
 * Same, for a semester rollup: everything the oracle's CIE feeds is dropped,
 * the counts and credits it does not are kept.
 */
function slimSummary(summary: Record<string, unknown>) {
  const {
    sgpaConfirmed: _sgpaConfirmed, sgpaProjected: _sgpaProjected,
    percentConfirmed: _percentConfirmed, percentProjected: _percentProjected,
    atRisk: _atRisk, impossible: _impossible, ...rest
  } = summary;
  return rest;
}

describe("parity with the Python engine", () => {
  it("has a corpus worth trusting", () => {
    expect(courses.length).toBeGreaterThan(500);
    expect(semesters.length).toBeGreaterThan(50);
    // A corpus with no blanks would not test the absence-is-not-zero rule.
    expect(courses.some(({ course }) => course.ese === "")).toBe(true);
    expect(courses.some(({ expected }) => expected.assessed === false)).toBe(true);
  });

  it("evaluates all 600 courses identically", () => {
    const mismatches: string[] = [];
    courses.forEach(({ course, expected }, i) => {
      const got = slim(evaluate(course));
      const a = JSON.stringify(got);
      const b = JSON.stringify(slimExpected(expected));
      if (a !== b) mismatches.push(`case ${i}\n  ts: ${a}\n  py: ${b}`);
    });
    expect(mismatches.slice(0, 3).join("\n")).toBe("");
    expect(mismatches.length).toBe(0);
  });

  it("rolls up every semester identically", () => {
    const mismatches: string[] = [];
    semesters.forEach(({ courses: rows, summary }, i) => {
      const got = JSON.stringify(slimSummary(summarise(rows) as unknown as Record<string, unknown>));
      const want = JSON.stringify(slimSummary(summary));
      if (got !== want) mismatches.push(`semester ${i}\n  ts: ${got}\n  py: ${want}`);
    });
    expect(mismatches.slice(0, 3).join("\n")).toBe("");
    expect(mismatches.length).toBe(0);
  });
});
