/**
 * Differential test: the TypeScript engine must agree with the Python one.
 *
 * The fixture is generated by tools/parity_dump.py from a seeded synthetic
 * corpus - every course type, marks present and absent, attendance either side
 * of both thresholds, duty leave inside and outside the cap. Hand-written
 * tests share the blind spots of whoever wrote the code; this does not.
 *
 * Regenerate the fixture whenever the Python engine changes, and never edit it
 * by hand - a fixture edited to make a test pass proves nothing.
 *
 * Some fields are excluded from the comparison below, because the Python
 * oracle carries the very defects p0-engine-correctness fixes: its fixture
 * values for them are the wrong answer, not the spec. Regenerating the
 * fixture would only re-pin these tests to the bugs, so it stays byte
 * identical and the comparison narrows instead. The attendance exclusions
 * below are per field rather than per object: where only part of an object
 * moved, the rest stays in, because a field the oracle still gets right is
 * evidence worth keeping. Direct coverage for everything dropped lives in
 * `core.test.ts`.
 *
 *   - `attendance`, `eligible`, `attMarks` (task 1): the oracle reads a blank
 *     attendance field as a full 100%.
 *   - `cie`, `total`, `grade`, `failedReason`, `needPass`, `needTarget`,
 *     `maxPossibleGrade`, `status` (task 1): the oracle never spends
 *     attendance inside the CIE, so every number derived from the CIE differs
 *     by up to the 5 marks of R 7.5.ii. The same goes for the semester
 *     rollup's SGPA, percentage, at-risk and impossible fields.
 *   - `plan.skip`, `plan.attend`, `attBand.attend` (task 8): the oracle
 *     credits duty leave once against today's `held`, then asks how many
 *     classes may be skipped or must be attended - questions whose `held`,
 *     and so whose 10% relaxation, is larger. Those three numbers answer a
 *     denominator that no longer applies. Only they moved, and only on the
 *     plans where a frozen credit can be wrong at all - where the claim
 *     exceeds the cap, or today's 100% ceiling clips it. 128 of the corpus's
 *     329 surplus plans and 29 of its 130 deficit plans are of that kind:
 *     `plan.skip` differs on 90 of those 128 (the other 38 floor to the same
 *     integer either way), `plan.attend` on all 29, and `attBand.attend` on
 *     29. The other nine fields of the two objects differ on none, so those
 *     nine are still compared - `plan.current` above all, the one field of
 *     `plan` that `effectiveAttendance` reads and so the plan's only route
 *     into the CIE, which makes it the fixture's standing evidence that this
 *     task moved nothing downstream of it.
 *   - `creditsConfirmed` and `assessed` in the rollup (task 10 fix 2): the
 *     oracle grades a course off a CIE that is short an unmarked component,
 *     reading a blank series exam as a zero. 43 of the 276 courses across the
 *     corpus semesters are assessed with a component still unmarked, and on 6
 *     of those this engine withholds the grade. Four of the six have an ESE
 *     recorded, so the oracle derives a grade for them (three Fs that are not
 *     certain - the highest CIE each can still reach clears the pass - and one
 *     A+ that its own unmarked component can only raise); the other two have
 *     no ESE, so the oracle withholds too and nothing moves. Those four move
 *     `creditsConfirmed` on 4 of the 60 semesters (21 vs 23, 11 vs 16, 15 vs
 *     19, 19 vs 22) and `assessed` on 1, where one of them is also debarred
 *     and so leaves the projection with its grade. What is lost is real:
 *     `creditsConfirmed` is a field these tasks move, and it was the fixture's
 *     standing check that credits enter and leave `confirmed` for the right
 *     reasons. The property test at the foot of this file carries that check
 *     instead, over the same 60 semesters and without the oracle. `pending`,
 *     `credits` and `lowAttendance` are unaffected - measured, 0 diffs on all
 *     three across all 60 - and stay in.
 *
 * One further field is dropped and it is not an exclusion at all: `unsettled`
 * (task 10 fix 1) has no counterpart in the fixture, because the Python engine
 * has no notion of an unsettled CIE. There is no oracle value to compare it
 * against, so nothing is given up by leaving it out.
 *
 * What is left of the rollup after all that is `pending`, `credits` and
 * `lowAttendance`, and it is worth saying plainly that this is thin. The
 * remaining evidence for the rollup is `core.test.ts`.
 *
 * EVERY MEASURED COUNT ABOVE IS ALSO AN ASSERTION - see "the header's counts
 * are measured, not remembered" at the foot of this file. Two of them have
 * been wrong before, once as a plain error and once as a real number stated
 * against the wrong predicate, and nothing was checking either. A figure that
 * cannot be re-derived does not belong in this header.
 *
 * What is left per course is worth stating exactly, since the exclusion list
 * above is long - and the per-course `assessed` is not the rollup field of
 * the same name and is still compared. Per course the comparison still
 * asserts `cieMax`, `eseMax`, `ese`,
 * `eseCutoff`, `assessed`, `credits`, `target`, and nine attendance fields:
 * `plan`'s raw and duty-leave-adjusted percentages, its claimed/credited/
 * wasted split and its surplus-or-deficit verdict, plus `attBand`'s earned
 * marks, next band and that band's floor. What it no longer asserts, per
 * course, is `Evaluation`'s own attendance readout and the eligibility and
 * CIE mark that hang off it, the CIE and everything the CIE feeds, and the
 * three moved plan numbers - and in the semester rollup, the same CIE-fed
 * figures. For all of those the evidence is `core.test.ts`, not this file.
 */
import { describe, expect, it } from "vitest";
import fixture from "./parity.json";
import { GRADE_POINTS, evaluate, isIncomplete, sgpa, summarise } from "../index";
import type { Course, Evaluation, Grade } from "../types";

interface Expected {
  cie: number; cieMax: number; eseMax: number; ese: number | null;
  eseCutoff: number; total: number | null; grade: string | null;
  failedReason: string; attendance: number; eligible: boolean;
  assessed: boolean; attMarks: number | null; credits: number;
  needPass: { value: number; possible: boolean; text: string; binding: string };
  needTarget: { value: number; possible: boolean; text: string; binding: string };
  target: string; maxPossibleGrade: string; status: string;
  plan: PlanFields | null;
  attBand: BandFields | null;
}

/**
 * The `plan` and `attBand` fields the oracle still agrees with, structurally
 * so that one reducer serves both sides. `AttendancePlan` and
 * `AttendanceBand` satisfy these; the moved keys are simply absent.
 */
interface PlanFields {
  raw: number; current: number; dlClaimed: number;
  dlCredited: number; dlWasted: number; state: string;
}
interface BandFields { earned: number; nextMarks: number | null; atPct: number | null; }

/** Drops `skip`/`attend`, keeps the six the fixture is still right about. */
const slimPlan = (plan: PlanFields | null) => plan === null ? null : {
  raw: plan.raw, current: plan.current, dlClaimed: plan.dlClaimed,
  dlCredited: plan.dlCredited, dlWasted: plan.dlWasted, state: plan.state,
};

/** Drops `attend`, keeps the three the fixture is still right about. */
const slimBand = (band: BandFields | null) => band === null ? null : {
  earned: band.earned, nextMarks: band.nextMarks, atPct: band.atPct,
};

const courses = fixture.courses as unknown as Array<{ course: Course; expected: Expected }>;
const semesters = fixture.semesters as unknown as Array<{
  courses: Course[];
  summary: Record<string, unknown>;
}>;

/**
 * Reduce an Evaluation to exactly the fields the fixture records, minus the
 * ones the Python oracle gets wrong (see file header).
 */
function slim(ev: Evaluation) {
  return {
    cieMax: ev.cieMax, eseMax: ev.eseMax, ese: ev.ese, eseCutoff: ev.eseCutoff,
    assessed: ev.assessed, credits: ev.credits, target: ev.target,
    plan: slimPlan(ev.plan), attBand: slimBand(ev.attBand),
  };
}

/** Same fields as `slim`, pulled off the Python fixture's recorded shape. */
function slimExpected(expected: Expected) {
  const {
    attendance: _attendance, eligible: _eligible, attMarks: _attMarks,
    cie: _cie, total: _total, grade: _grade, failedReason: _failedReason,
    needPass: _needPass, needTarget: _needTarget,
    maxPossibleGrade: _maxPossibleGrade, status: _status,
    plan, attBand, ...rest
  } = expected;
  return { ...rest, plan: slimPlan(plan), attBand: slimBand(attBand) };
}

/**
 * Same, for a semester rollup: everything the oracle's CIE feeds is dropped,
 * the counts and credits it does not are kept.
 */
function slimSummary(summary: Record<string, unknown>) {
  const {
    sgpaConfirmed: _sgpaConfirmed, sgpaProjected: _sgpaProjected,
    percentConfirmed: _percentConfirmed, percentProjected: _percentProjected,
    atRisk: _atRisk, impossible: _impossible,
    unsettled: _unsettled, creditsConfirmed: _creditsConfirmed,
    assessed: _assessed, ...rest
  } = summary;
  return rest;
}

describe("parity with the Python engine", () => {
  it("has a corpus worth trusting", () => {
    expect(courses.length).toBeGreaterThan(500);
    expect(semesters.length).toBeGreaterThan(50);
    // A corpus with no blanks would not test the absence-is-not-zero rule.
    expect(courses.some(({ course }) => course.ese === "")).toBe(true);
    expect(courses.some(({ expected }) => expected.assessed === false)).toBe(true);
  });

  it("evaluates all 600 courses identically", () => {
    const mismatches: string[] = [];
    courses.forEach(({ course, expected }, i) => {
      const got = slim(evaluate(course));
      const a = JSON.stringify(got);
      const b = JSON.stringify(slimExpected(expected));
      if (a !== b) mismatches.push(`case ${i}\n  ts: ${a}\n  py: ${b}`);
    });
    expect(mismatches.slice(0, 3).join("\n")).toBe("");
    expect(mismatches.length).toBe(0);
  });

  it("rolls up every semester identically", () => {
    const mismatches: string[] = [];
    semesters.forEach(({ courses: rows, summary }, i) => {
      const got = JSON.stringify(slimSummary(summarise(rows) as unknown as Record<string, unknown>));
      const want = JSON.stringify(slimSummary(summary));
      if (got !== want) mismatches.push(`semester ${i}\n  ts: ${got}\n  py: ${want}`);
    });
    expect(mismatches.slice(0, 3).join("\n")).toBe("");
    expect(mismatches.length).toBe(0);
  });
});

/**
 * What the narrowed rollup fields lost, asserted over the whole corpus instead
 * of against the oracle.
 *
 * `creditsConfirmed` and `assessed` are no longer compared to the Python
 * numbers, so the protection they carried - that credits enter and leave
 * `confirmed` for the right reasons, on real data rather than on hand-picked
 * examples - has to come from somewhere. It comes from a property: a course's
 * credits are confirmed exactly when its grade is settled. That ranges over
 * all 60 corpus semesters and 276 courses, it does not need an oracle, and it
 * fails the moment a course is dropped from or added to `confirmed` for any
 * reason other than having a grade.
 */
describe("the rollup counts what it says it counts", () => {
  const settled = (c: Course) => {
    const ev = evaluate(c);
    return ev.grade !== null && !isIncomplete(ev.grade) ? ev : null;
  };

  it("confirms exactly the credits of the courses whose grade is settled", () => {
    const bad: string[] = [];
    semesters.forEach(({ courses: rows }, i) => {
      const got = summarise(rows);
      const graded = rows.map(settled).filter((ev): ev is Evaluation => ev !== null);
      const credits = graded.reduce((sum, ev) => sum + ev.credits, 0);
      // `settled` has already excluded null, "I" and "W", so every grade left
      // here carries a grade point.
      const mean = sgpa(graded.map((ev) => [ev.credits, GRADE_POINTS[ev.grade as Grade]]));
      if (got.creditsConfirmed !== credits) {
        bad.push(`semester ${i}: creditsConfirmed ${got.creditsConfirmed} vs ${credits}`);
      }
      if (got.sgpaConfirmed !== mean) {
        bad.push(`semester ${i}: sgpaConfirmed ${got.sgpaConfirmed} vs ${mean}`);
      }
      // A confirmed credit is always a registered one, and the registered
      // count is every course that is not a withdrawal or an incomplete.
      const registered = rows.filter((c) => !isIncomplete(evaluate(c).grade))
        .reduce((sum, c) => sum + evaluate(c).credits, 0);
      if (got.credits !== registered) bad.push(`semester ${i}: credits ${got.credits} vs ${registered}`);
      if (got.creditsConfirmed > got.credits) bad.push(`semester ${i}: confirmed exceeds registered`);
      // `assessed` is the projection's population: every settled course is in
      // it, and nothing outside the registered set ever is.
      if (got.assessed < graded.length) bad.push(`semester ${i}: assessed ${got.assessed} < graded ${graded.length}`);
      if (got.assessed > rows.filter((c) => !isIncomplete(evaluate(c).grade)).length) {
        bad.push(`semester ${i}: assessed ${got.assessed} exceeds the registered count`);
      }
    });
    expect(bad.slice(0, 3).join(" | ")).toBe("");
    expect(bad.length).toBe(0);
  });

  it("is not a vacuous property on this corpus", () => {
    // The property only bites where a grade is withheld, so the corpus has to
    // contain such courses - and it is exactly the six that took the rollup
    // fields out of the oracle comparison in the first place. Measured over
    // the 276 semester courses: 43 are assessed with a component still
    // unmarked, and on these six that withholds a grade the oracle derives.
    const rows = semesters.flatMap(({ courses: c }) => c);
    const unmarked = rows.filter((c) => { const ev = evaluate(c); return ev.assessed && ev.cieUnmarked; });
    const withheld = unmarked.filter((c) => evaluate(c).grade === null);
    expect(rows.length).toBe(276);
    expect(unmarked.length).toBe(43);
    expect(withheld.length).toBe(6);
    // And at least one semester really does confirm fewer credits than it
    // registers because of them, or the assertion above would prove nothing.
    expect(semesters.some(({ courses: c }) => {
      const got = summarise(c);
      return got.creditsConfirmed < got.credits;
    })).toBe(true);
  });
});

/**
 * Every measured count in this file's header, re-derived.
 *
 * The header is where this branch decided measured counts should live, and it
 * is the file whose counts have already been wrong twice - once a plain error
 * ("6 of the 276" when it was 43) and once a real number stated against the
 * wrong predicate. Nine figures sat in it with nothing checking them, so they
 * were right by luck rather than by construction. The countermeasure the
 * branch found for comments elsewhere is to make the number an assertion; this
 * applies it here.
 *
 * A figure that cannot be re-derived does not belong in the header. If one of
 * these fails, fix the header rather than the expectation - the fixture is
 * frozen, so a moved number means the ENGINE moved and the exclusion note is
 * now describing something else.
 */
describe("the header's counts are measured, not remembered", () => {
  const rows = semesters.flatMap(({ courses: c }) => c);

  it("re-derives the rollup exclusion counts", () => {
    const unmarked = rows.filter((c) => {
      const ev = evaluate(c);
      return ev.assessed && ev.cieUnmarked;
    });
    const withheld = unmarked.filter((c) => evaluate(c).grade === null);
    expect(rows.length).toBe(276);
    expect(unmarked.length).toBe(43);
    expect(withheld.length).toBe(6);
    // The four the oracle grades anyway, because they have an ESE recorded.
    expect(withheld.filter((c) => evaluate(c).ese !== null).length).toBe(4);

    const confirmedDiffs: string[] = [];
    let assessedDiffs = 0, pendingDiffs = 0, creditsDiffs = 0, lowAttendanceDiffs = 0;
    semesters.forEach(({ courses: c, summary }) => {
      const got = summarise(c);
      if (got.creditsConfirmed !== summary["creditsConfirmed"]) {
        confirmedDiffs.push(`${got.creditsConfirmed} vs ${summary["creditsConfirmed"]}`);
      }
      if (got.assessed !== summary["assessed"]) assessedDiffs += 1;
      if (got.pending !== summary["pending"]) pendingDiffs += 1;
      if (got.credits !== summary["credits"]) creditsDiffs += 1;
      if (JSON.stringify(got.lowAttendance) !== JSON.stringify(summary["lowAttendance"])) {
        lowAttendanceDiffs += 1;
      }
    });
    expect(semesters.length).toBe(60);
    expect(confirmedDiffs).toEqual(["21 vs 23", "11 vs 16", "15 vs 19", "19 vs 22"]);
    expect(assessedDiffs).toBe(1);
    // The three rollup fields still compared. If any of these stops being 0
    // the comparison above is failing anyway, but stating it here is what
    // makes the header's "0 diffs on all three" a checked claim.
    expect([pendingDiffs, creditsDiffs, lowAttendanceDiffs]).toEqual([0, 0, 0]);
  });

  it("re-derives the duty-leave exclusion counts", () => {
    // "Only on the plans where a frozen credit can be wrong at all - where the
    // claim exceeds the cap, or today's 100% ceiling clips it." That predicate,
    // spelled out: some claimed leave went to waste, or crediting it would push
    // the attended count past the classes held.
    let surplus = 0, deficit = 0, surplusFrozen = 0, deficitFrozen = 0;
    let skipDiffs = 0, attendDiffs = 0, bandAttendDiffs = 0, otherPlanDiffs = 0;
    for (const { course, expected } of courses) {
      const plan = expected.plan as (PlanFields & { skip: number | null; attend: number | null }) | null;
      if (plan === null) continue;
      const ev = evaluate(course);
      // The fixture recorded a plan, so this course has attendance evidence
      // and `evaluate` builds one too - the shapes are compared field by
      // field above, which is what makes that safe to assert here.
      if (ev.plan === null || ev.attBand === null) throw new Error(`no plan for ${course.code}`);
      const attended = Number(course.attended ?? 0);
      const held = Number(course.held ?? 0);
      const frozen = plan.dlWasted > 0 || (held > 0 && attended + plan.dlCredited > held);
      if (plan.state === "surplus") { surplus += 1; if (frozen) surplusFrozen += 1; }
      if (plan.state === "deficit") { deficit += 1; if (frozen) deficitFrozen += 1; }
      if (ev.plan.skip !== plan.skip) skipDiffs += 1;
      if (ev.plan.attend !== plan.attend) attendDiffs += 1;
      const band = expected.attBand as (BandFields & { attend: number | null }) | null;
      if (band !== null && ev.attBand.attend !== band.attend) bandAttendDiffs += 1;
      // "The other nine fields of the two objects differ on none": the six of
      // `plan` and the three of `attBand` that `slimPlan`/`slimBand` keep.
      if (JSON.stringify(slimPlan(ev.plan)) !== JSON.stringify(slimPlan(plan))) otherPlanDiffs += 1;
      if (band !== null
          && JSON.stringify(slimBand(ev.attBand)) !== JSON.stringify(slimBand(band))) {
        otherPlanDiffs += 1;
      }
    }
    expect(courses.length).toBe(612);
    expect([surplus, deficit]).toEqual([329, 130]);
    expect([surplusFrozen, deficitFrozen]).toEqual([128, 29]);
    expect(skipDiffs).toBe(90);
    expect(attendDiffs).toBe(29);
    expect(bandAttendDiffs).toBe(29);
    expect(otherPlanDiffs).toBe(0);
  });
});
